version: "3"
services:
  platform:
    image: platform
    container_name: platform
    build:
      context: images/platform
      args:
        - timezone=Europe/Moscow

  app:
    image: app
    container_name: app
    build:
      context: images/app
      args:
        - username=user
    depends_on:
      - platform

  node:
    image: node
    container_name: node
    build:
      context: images/node
    depends_on:
      - app

  node-telegram-gw:
    image: node-telegram-gw
    container_name: tlgrm-gw-srv-01
    restart: always
    build:
      context: images/node-app
      args:
        - giturl=https://github.com/timmson/mbt-telegram-gw.git
    ports:
      - "16080:8080"
    depends_on:
      - node

  go:
    image: go
    container_name: go
    build:
      context: images/go
    depends_on:
      - app

  go-telegram-gw:
    image: go-telegram-gw
    container_name: tlgrm-gw-srv-02
    restart: always
    build:
      context: images/go-app
      args:
        - giturl=https://github.com/timmson/mbt-telegram-gw-go.git
    ports:
      - "26080:8080"
    depends_on:
      - go