version: "3"
services:
  platform:
    image: platform
    hostname: platform
    build:
      context: images/platform
      args:
        - timezone=Europe/Moscow

  app:
    image: app
    hostname: app
    build:
      context: images/app
      args:
        - username=user
    depends_on:
      - platform

#  node:
#    image: node
#    hostname: node
#    build:
#      context: images/node
#    depends_on:
#      - app

  go:
    image: go
    hostname: go
    build:
      context: images/go
    depends_on:
      - app

  go-telegram-gw:
    image: go-telegram-gw
    hostname: tlgrm-gw-srv-01
    build:
      context: images/go-app
      args:
        - giturl=https://github.com/timmson/mbt-telegram-gw-go.git
    ports:
      - "26080:8080"
    depends_on:
      - go