name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Platform image
      run: docker build -t timmson/mbt-platform-v2:platform .

    - name: Build the Docker Java image
      run: docker build -t timmson/mbt-platform-v2:java java/.

    - name: Build the Docker NodeJs image
      run: docker build -t timmson/mbt-platform-v2:node node/.
